### ISSUE TITLE
Unexpected result from 'Extract QA Bands' tool

### ISSUE THREAD

**Issue by sadareen** [USGS-EROS/landsat-qa-arcgis-toolbox#2]
Hi, I've been using the 'Extract QA Bands' tool provided with the 'Landsat QA ArcGIS Toolbox' and I would like to discuss about an unexpected result. After using the 'Decode QA' tool for a Landsat 8 'pixel_qa' scene, ArcMap loaded the resulting band into Table of Contents in the active data frame. This band did not have any attribute called 'Fill' which may be normal in landsat scenes. However, when I proceeded to use the 'Extract QA Bands' to extract 'Fill' Values why does the result return the whole band full of pixel value 1? This is strange because the decoded band does not have any 'Fill Values'. The tool did not report any error either. How does the 'Extract QA Bands' tool treat decoded bands that do not have a particular attribute? Shouldn't it return an error message saying something like, 'This band does not contain any 'Fill Value' pixels'. If not, do you have any suggestions how to interpret the result?

My aim is to test the tool on a pixel_qa scene where there are actual 'Fill Values'. I remember reading in one of the product guides that 'Fill Values' are to be avoided. This particular Landsat 8 scene that I analysed may not have any Fill Values but I anyway used it to test the tool. If you know of any landsat 8 scene that has 'fill values' kindly share the scene id. I downloaded the pixel_qa band that i analysed from espa.cr.usgs.gov and following are the scene details: LANDSAT_SCENE_ID = "LC81690572016079LGN01"    LANDSAT_PRODUCT_ID = "LC08_L1TP_169057_20160319_20170328_01_T1"
I've also added a screenshot of ArcMap with the decode and extract results.
![fill](https://user-images.githubusercontent.com/30730049/32131352-9d95a2e8-bbc9-11e7-9ca7-ce9dddc7d38e.png)

**Comment by saeedarab** [comment]
Hello,

Thank you for your feedback about "Extract QA Bands" tool and sorry for the slow response. This issue has been identified and resolved in 1.3 release. Please let us know if you have additional questions.

Thank you
